language: java
jdk:
  - openjdk8
script: mvn install
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GH_TOKEN
  file_glob: true
  file:
    - "target/LWCX-2.1.8.jar"
  on:
    tags: true
